// <auto-generated />
using System;
using DataServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataServer.Migrations
{
    [DbContext(typeof(ClientContext))]
    partial class ClientContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("DataServer.Models.Client", b =>
                {
                    b.Property<string>("IPAddress")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedJobs")
                        .HasColumnType("INTEGER");

                    b.HasKey("IPAddress", "Port");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            IPAddress = "192.168.1.1",
                            Port = 8080,
                            CompletedJobs = 0
                        },
                        new
                        {
                            IPAddress = "192.168.1.2",
                            Port = 8081,
                            CompletedJobs = 0
                        },
                        new
                        {
                            IPAddress = "192.168.1.3",
                            Port = 8082,
                            CompletedJobs = 0
                        },
                        new
                        {
                            IPAddress = "192.168.1.4",
                            Port = 8083,
                            CompletedJobs = 0
                        },
                        new
                        {
                            IPAddress = "192.168.1.5",
                            Port = 8084,
                            CompletedJobs = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
